INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 13:00:00', N'Чемпионат мира', N'football', N'Тунис', N'Австралия')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 16:00:00', N'Чемпионат мира', N'football', N'Польша', N'Саудовская Аравия')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 19:00:00', N'Чемпионат мира', N'football', N'Франция', N'Дания')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 22:00:00', N'Чемпионат мира', N'football', N'Аргентина', N'Мексика')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 01:30:00', N'НХЛ', N'hockey', N'Филадельфия', N'Питтсбург')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 04:00:00', N'НХЛ', N'hockey', N'Баффало', N'Нью-Джерси')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 04:00:00', N'НХЛ', N'hockey', N'Вегас', N'Сиэтл')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 04:00:00', N'НХЛ', N'hockey', N'Детройт', N'Аризона')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 17:15:00', N'Элитсериен', N'hockey', N'Оскарсхамн', N'Тимре')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 17:15:00', N'Элитсериен', N'hockey', N'Фрелунда', N'Линчеппинг')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 20:00:00', N'Элитсериен', N'hockey', N'Брюнес', N'ХВ-71')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 20:00:00', N'Элитсериен', N'hockey', N'Мальмо', N'Векшё')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 20:00:00', N'Элитсериен', N'hockey', N'Рёгле', N'Лулео')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 20:00:00', N'Элитсериен', N'hockey', N'Ферьестад', N'Эребру')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 20:00:00', N'Элитсериен', N'hockey', N'Шеллефтео', N'Лександ')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 15:20:00', N'Кубок Дэвиса', N'tennis', N'Италия', N'Канада')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 01:00:00', N'НБА', N'basketball', N'Шарлотт Хорнетс', N'Миннесота Тимбервулвз')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 03:00:00', N'НБА', N'basketball', N'Орландо Мэджик', N'Фмладельфия Сиксерс')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 03:30:00', N'НБА', N'basketball', N'Нью-Йорк Никс', N'Портленд Трэйл Блэйзерс')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 04:00:00', N'НБА', N'basketball', N'Бостон Селтикс', N'Сакраменто Кингз')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 22:00:00', N'Серия А', N'basketball', N'Венеция', N'Тренто')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 22:30:00', N'Серия А', N'basketball', N'Паллаканестро Триесте', N'Брешия')
INSERT INTO [dbo].[Events] ([Date], [Name], [EventType], [TeamA], [TeamB]) VALUES (N'2022-11-26 20:00:00', N'СуперЛега', N'volleyball', N'Трентино', N'Милан')
